// UI
export const ARE_DECK_TAGS_INCLUDED = "ARE_DECK_TAGS_INCLUDED";
export const STUDIED_CARDS_CHART_TOTAL = "STUDIED_CARDS_CHART_TOTAL";
export const STUDY_TIME_CHART_TOTAL = "STUDY_TIME_CHART_TOTAL";

// Auth
export const ACCESS_TOKEN = "ACCESS_TOKEN";

// Sorting
export const DECKS_SORT = "DECKS_SORT";
export const STUDY_DECKS_SORT = "STUDY_DECKS_SORT";
export const CARDS_SORT = "CARDS_SORT";
